### ISSUE TITLE
[Feature Request]: Add support for building BOMs from `cargo build`'s `--build-plan` output

### ISSUE THREAD

**Issue by platten** [CycloneDX/cyclonedx-rust-cargo#175]
## Context:
I am working on the [enarx project](https://github.com/enarx/enarx) which supports different feature sets/dependency graphs based on which features and/or binary targets we are compiling for (e.g. for Windows/MacOS/AARCH64 we do not include the `enarx-shim-sgx` and `enarx-shim-kvm` binary-dependency subcrates from our workspace). One way to see the differences is on the dependencies used for the various targets/enabled features is to run ` cargo build -Z unstable-options --build-plan  | jq '.inputs'` which outputs a list of paths to the `Cargo.toml` used for building a binary.

## Request:
I would recommend a mode for `cargo cyclonedx` which could take parameters that would be used when running `cargo build` (target, features, etc), use that to generate a build-plan, and use the inputs from that buildplan to construct a BOM. 

Thoughts?

**Comment by jadamcrain** [comment]
I've been doing something similar to create my own BOMs and license reports, namely use the types in `cargo-metadata` to parse the JSON output of the build.

I really like this approach because it is the "ground truth" of what is actually happening in the build.

One challenge is sorting through the artifacts that are build-only vs things that actually make it into the compiled binary. Many of these things are just dependencies to compile `build.rs` for dependencies of the main crate.

One thing that's great about this approach is that it respects cargo features.  If I build with a subset of features, only the dependencies under that configuration go into the BOM.

**Comment by Shnatsel** [comment]
Build-plan is nightly-only, but I've added the ability to select the right features in #512 and the right target in #513, and also ported the tool to `cargo metadata` in #496 so that we won't diverge from Cargo's ground truth.
